openapi: 3.0.3
info:
  title: 'Lion Roaring'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/v1/cms/gallery:
    post:
      summary: 'Get gallery'
      operationId: getGallery
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"message\": \"Gallery\",\n\"status\": true,\n\"gallery\": [\n    {\n      \"image_url\": \"http://127.0.0.1:8000/storage/gallery/kg4vGiEpej4HXuc50ZVKQC2Agjvn6wj3rMygAOxu.jpg\"\n    },\n  ]\n}"
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No gallery found'
                  status: false
                properties:
                  message:
                    type: string
                    example: 'No gallery found'
                  status:
                    type: boolean
                    example: false
      tags:
        - 'CMS Management'
      security: []
  /api/v1/cms/faq:
    post:
      summary: 'Get FAQ'
      operationId: getFAQ
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"message\": \"FAQ\",\n\"status\": true,\n\"faq\": [\n   {\n     \"title\": \"Are there any transport facilities available for the staff members?\",\n     \"content\": \"This is the second item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.\"\n  },\n]\n}"
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No FAQ found'
                  status: false
                properties:
                  message:
                    type: string
                    example: 'No FAQ found'
                  status:
                    type: boolean
                    example: false
      tags:
        - 'CMS Management'
      security: []
  /api/v1/cms/principle-and-business:
    post:
      summary: 'Get Principal and Business Model'
      operationId: getPrincipalAndBusinessModel
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"message\": \"Principal and Business\",\n\"status\": true,\n\"principleAndBusiness\": {\n  \"banner_image_url\": \"http://127.0.0.1:8000/storage/principle-and-business/iJt84RS9xLxfytBLynRBg4huIy9HfhfHWwJXEftc.jpg\",\n  \"banner_title\": \"OUR PRINCIPLE AND BUSINESS MODEL\",\n  \"image_url\": \"http://127.0.0.1:8000/storage/principle-and-business/CzFIynj2rOY7JSYtOVt1KtIKMFxFrP2A38J7Hwpz.png\",\n  \"title\": \"OUR PRINCIPLE AND BUSINESS MODEL\",\n  \"content\": \"<p><strong>These seven primodial spirits in God is the Core principle that Lion Roaring has adopted in order to pursue perfected love in our soul and become like Christ. And the ultimate goal in Lion Roaring is to be able to bring Heaven on Earth.</strong>\n}\n}"
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No Principal and Business found'
                  status: false
                properties:
                  message:
                    type: string
                    example: 'No Principal and Business found'
                  status:
                    type: boolean
                    example: false
      tags:
        - 'CMS Management'
      security: []
  /api/v1/cms/ecclesia-associations:
    post:
      summary: 'Get Ecclesia Associations'
      operationId: getEcclesiaAssociations
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"message\": \"Ecclesia Associations\",\n\"status\": true,\n\"ecclesiaAssociations\": {\n  \"banner_image_url\": \"http://127.0.0.1:8000/storage/principle-and-business/iJt84RS9xLxfytBLynRBg4huIy9HfhfHWwJXEftc.jpg\",\n  \"banner_title\": \"OUR ECCLESIA ASSOCIATION\",\n  \"title\": \"OUR ECCLESIA ASSOCIATION\",\n  \"content\": \"<p><strong>These seven primodial spirits in God is the Core principle that Lion Roaring has adopted in order to pursue perfected love in our soul and become like Christ. And the ultimate goal in Lion Roaring is to be able to bring Heaven on Earth.</strong>\n  }\n}"
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No Ecclesia Associations found'
                  status: false
                properties:
                  message:
                    type: string
                    example: 'No Ecclesia Associations found'
                  status:
                    type: boolean
                    example: false
      tags:
        - 'CMS Management'
      security: []
  /api/v1/cms/our-organization:
    post:
      summary: 'Get Organization'
      operationId: getOrganization
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Organization
                  status: true
                  organization:
                    banner_section:
                      banner_image_url: 'http://127.0.0.1:8000/storage/organization/paSVDc0EoYdGYGzvDpbK3akKyGkpEQII5SXIKt9c.jpg'
                      banner_title: 'OUR ORGANIZATION'
                    about_section:
                      about_section_image_1: 'http://127.0.0.1:8000/storage/organization/ygqFzHisBYM8pAoWIWf4WJuK0QIP6KjGTEHGfpgy.png'
                      about_section_image_2: 'http://127.0.0.1:8000/storage/organization/WqrUEHEAP8nsL4kRC0Qr2zo4tyI9cKVSjcQeWUG5.png'
                      about_section_image_3: 'http://127.0.0.1:8000/storage/organization/gNMs84RgkxLAcYAFlAq06YE3BHexYN0IeOZHADIO.png'
                      about_section_image_4: 'http://127.0.0.1:8000/storage/organization/UvaKMc7pcWKDGxTN20MF1aTK8wmfZPRH2LA1XLbE.png'
                      about_section_image_5: 'http://127.0.0.1:8000/storage/organization/Btj1lC8MDyDrn5oVwoJRfZarYsYQefTin5wIJlyl.png'
                    project_section:
                      project_section_title: 'LION ROARING INNOVATION CENTERS OVERVIEW'
                      project_section_sub_title: 'KINGSHIP AUTHORITY'
                      project_section_description: 'Lion Roaring Innovation Centers'
                    project_section_details:
                      -
                        title: 'Science & Technology Innovation Center'
                        details: '<ul><li>Digital Transformation</li><li>Quantum Technology</li><li>BioTech</li><li>Telecommunication</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Healthcare & Medicine Innovation Center'
                        details: '<ul><li>Miracle Healing</li><li>Oil &amp; Herb Medicine</li><li>Natural Nutrition Intake</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Farming, Food & Nutrition Innovation Center'
                        details: '<ul><li>Agriculture</li><li>Distribution</li><li>Preserve &amp; Packaging</li><li>Farming</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Lion Roaring Foundation'
                        details: '<ul><li>US National Status</li><li>Change our Status</li><li>Training &amp; mentorship</li><li>Restoration of cities &amp; State via Education</li><li>Private Bank, Trust, 1099a, W4, etc.</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Animal Shelter & Training Innovation Center'
                        details: '<ul><li>Training</li><li>Rescue/Safari</li><li>Boarding</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Music, Media, Innovation Center'
                        details: '<ul><li>Music/Worship &amp; Arts</li><li>Harp &amp; Shofar, others</li><li>Dancing &amp; Painting</li></ul><p><br>&nbsp;</p>'
                      -
                        title: 'Entertainment & Arts Innovation Center'
                        details: '<ul><li>Video &amp; Photo</li><li>Media &amp; Entertainment</li><li>Marketing &amp; Publisher</li></ul><p><br>&nbsp;</p>'
                properties:
                  message:
                    type: string
                    example: Organization
                  status:
                    type: boolean
                    example: true
                  organization:
                    type: object
                    properties:
                      banner_section:
                        type: object
                        properties:
                          banner_image_url:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/paSVDc0EoYdGYGzvDpbK3akKyGkpEQII5SXIKt9c.jpg'
                          banner_title:
                            type: string
                            example: 'OUR ORGANIZATION'
                      about_section:
                        type: object
                        properties:
                          about_section_image_1:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/ygqFzHisBYM8pAoWIWf4WJuK0QIP6KjGTEHGfpgy.png'
                          about_section_image_2:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/WqrUEHEAP8nsL4kRC0Qr2zo4tyI9cKVSjcQeWUG5.png'
                          about_section_image_3:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/gNMs84RgkxLAcYAFlAq06YE3BHexYN0IeOZHADIO.png'
                          about_section_image_4:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/UvaKMc7pcWKDGxTN20MF1aTK8wmfZPRH2LA1XLbE.png'
                          about_section_image_5:
                            type: string
                            example: 'http://127.0.0.1:8000/storage/organization/Btj1lC8MDyDrn5oVwoJRfZarYsYQefTin5wIJlyl.png'
                      project_section:
                        type: object
                        properties:
                          project_section_title:
                            type: string
                            example: 'LION ROARING INNOVATION CENTERS OVERVIEW'
                          project_section_sub_title:
                            type: string
                            example: 'KINGSHIP AUTHORITY'
                          project_section_description:
                            type: string
                            example: 'Lion Roaring Innovation Centers'
                      project_section_details:
                        type: array
                        example:
                          -
                            title: 'Science & Technology Innovation Center'
                            details: '<ul><li>Digital Transformation</li><li>Quantum Technology</li><li>BioTech</li><li>Telecommunication</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Healthcare & Medicine Innovation Center'
                            details: '<ul><li>Miracle Healing</li><li>Oil &amp; Herb Medicine</li><li>Natural Nutrition Intake</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Farming, Food & Nutrition Innovation Center'
                            details: '<ul><li>Agriculture</li><li>Distribution</li><li>Preserve &amp; Packaging</li><li>Farming</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Lion Roaring Foundation'
                            details: '<ul><li>US National Status</li><li>Change our Status</li><li>Training &amp; mentorship</li><li>Restoration of cities &amp; State via Education</li><li>Private Bank, Trust, 1099a, W4, etc.</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Animal Shelter & Training Innovation Center'
                            details: '<ul><li>Training</li><li>Rescue/Safari</li><li>Boarding</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Music, Media, Innovation Center'
                            details: '<ul><li>Music/Worship &amp; Arts</li><li>Harp &amp; Shofar, others</li><li>Dancing &amp; Painting</li></ul><p><br>&nbsp;</p>'
                          -
                            title: 'Entertainment & Arts Innovation Center'
                            details: '<ul><li>Video &amp; Photo</li><li>Media &amp; Entertainment</li><li>Marketing &amp; Publisher</li></ul><p><br>&nbsp;</p>'
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                              example: 'Science & Technology Innovation Center'
                            details:
                              type: string
                              example: '<ul><li>Digital Transformation</li><li>Quantum Technology</li><li>BioTech</li><li>Telecommunication</li></ul><p><br>&nbsp;</p>'
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No Organization found'
                  status: false
                properties:
                  message:
                    type: string
                    example: 'No Organization found'
                  status:
                    type: boolean
                    example: false
      tags:
        - 'CMS Management'
      security: []
  /api/v1/contact-us:
    post:
      summary: 'Store Contact Us'
      operationId: storeContactUs
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Thank you for contacting us'
                  status: true
                properties:
                  message:
                    type: string
                    example: 'Thank you for contacting us'
                  status:
                    type: boolean
                    example: true
      tags:
        - 'Contact Us'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'First Name of the user.'
                  example: John
                last_name:
                  type: string
                  description: 'Last Name of the user.'
                  example: Doe
                email:
                  type: string
                  description: 'Email of the user. Example:'
                  example: anjali.olson@example.org
                phone:
                  type: string
                  description: 'Phone of the user.'
                  example: '1234567890'
                message:
                  type: string
                  description: 'Message of the user.'
                  example: Hello
              required:
                - first_name
                - last_name
                - email
                - phone
                - message
      security: []
tags:
  -
    name: 'CMS Management'
    description: ''
  -
    name: 'Contact Us'
    description: ''
