<?php

return [
    'base_path' => base_path('docs/pma'),

    'sections' => [
        [
            'slug' => 'messaging',
            'title' => 'Messaging',
            'summary' => 'Chats, Team, and Mail.',
            'icon' => 'fa-solid fa-envelope',
            'file' => 'messaging.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'messaging',
        ],
        [
            'slug' => 'education',
            'title' => 'Education',
            'summary' => 'Topics, becoming tracks, and education files.',
            'icon' => 'fa-solid fa-book',
            'file' => 'education.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'education',
        ],
        [
            'slug' => 'bulletins',
            'title' => 'Bulletins',
            'summary' => 'Bulletin board, jobs, meetings, events, collaboration.',
            'icon' => 'fa-solid fa-clipboard-list',
            'file' => 'bulletins.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'bulletins',
        ],
        [
            'slug' => 'e-store',
            'title' => 'E-Store',
            'summary' => 'Products, orders, warehouses, promo codes, store CMS.',
            'icon' => 'fa-solid fa-cart-shopping',
            'file' => 'e-store.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'e_store',
        ],
        [
            'slug' => 'warehouse-store',
            'title' => 'Warehouse Store',
            'summary' => 'Warehouse-scoped products and orders.',
            'icon' => 'fa-solid fa-box',
            'file' => 'warehouse-store.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'warehouse_store',
        ],
        [
            'slug' => 'e-learning',
            'title' => 'E-Learning',
            'summary' => 'E-learning catalog and CMS.',
            'icon' => 'fa-solid fa-lightbulb',
            'file' => 'e-learning.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'e_learning',
        ],
        [
            'slug' => 'role-permission',
            'title' => 'Role Permission',
            'summary' => 'Roles and Spatie permissions.',
            'icon' => 'fa-solid fa-lock',
            'file' => 'role-permission.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'role_permission',
        ],
        [
            'slug' => 'membership-management',
            'title' => 'Membership Management',
            'summary' => 'Plans, members, payments, promo codes, settings.',
            'icon' => 'fa-solid fa-id-badge',
            'file' => 'membership-management.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'membership_management',
        ],
        [
            'slug' => 'all-members',
            'title' => 'All Members',
            'summary' => 'Partners / all members list.',
            'icon' => 'fa-solid fa-users',
            'file' => 'all-members.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'all_members',
        ],
        [
            'slug' => 'user-activity',
            'title' => 'User Activity',
            'summary' => 'Activity dashboard and activity list.',
            'icon' => 'fa-solid fa-chart-line',
            'file' => 'user-activity.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'user_activity',
        ],
        [
            'slug' => 'signup-rules',
            'title' => 'Signup Rules',
            'summary' => 'Registration and signup rule configuration.',
            'icon' => 'fa-solid fa-square-check',
            'file' => 'signup-rules.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'signup_rules',
        ],
        [
            'slug' => 'strategy',
            'title' => 'Strategy',
            'summary' => 'Strategy documents and management.',
            'icon' => 'fa-solid fa-flag',
            'file' => 'strategy.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'strategy',
        ],
        [
            'slug' => 'policy-guidance',
            'title' => 'Policy & Guidance',
            'summary' => 'Policy and guidance documents.',
            'icon' => 'fa-solid fa-folder-open',
            'file' => 'policy-guidance.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'policy_guidance',
        ],
        [
            'slug' => 'membership-self-service',
            'title' => 'Membership (Self-Service)',
            'summary' => 'Member-facing membership panel.',
            'icon' => 'fa-solid fa-credit-card',
            'file' => 'membership-self-service.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'membership',
        ],
        [
            'slug' => 'restore',
            'title' => 'Restore',
            'summary' => 'Recycle bin — Super Admin only.',
            'icon' => 'fa-solid fa-trash-can',
            'file' => 'restore.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'recycle_bin',
        ],
        [
            'slug' => 'donations',
            'title' => 'Donations',
            'summary' => 'Admin portal donations management.',
            'icon' => 'fa-solid fa-heart',
            'file' => 'donations.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'donations',
        ],
        [
            'slug' => 'newsletters',
            'title' => 'Newsletters',
            'summary' => 'Newsletter CMS.',
            'icon' => 'fa-solid fa-envelope',
            'file' => 'newsletters.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'newsletters',
        ],
        [
            'slug' => 'testimonials',
            'title' => 'Testimonials',
            'summary' => 'Testimonials list and create.',
            'icon' => 'fa-solid fa-quote-left',
            'file' => 'testimonials.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'testimonials',
        ],
        [
            'slug' => 'our-governance',
            'title' => 'Our Governance',
            'summary' => 'Governance CMS entries.',
            'icon' => 'fa-solid fa-briefcase',
            'file' => 'our-governance.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'our_governance',
        ],
        [
            'slug' => 'our-organizations',
            'title' => 'Our Organizations',
            'summary' => 'Organizations CMS entries.',
            'icon' => 'fa-solid fa-globe',
            'file' => 'our-organizations.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'our_organizations',
        ],
        [
            'slug' => 'organization-center',
            'title' => 'Organization Center',
            'summary' => 'Organization center CMS.',
            'icon' => 'fa-solid fa-building',
            'file' => 'organization-center.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'organization_center',
        ],
        [
            'slug' => 'services',
            'title' => 'Services',
            'summary' => 'Per-organization services CMS.',
            'icon' => 'fa-solid fa-gears',
            'file' => 'services.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'services',
        ],
        [
            'slug' => 'pages-cms',
            'title' => 'Pages (CMS)',
            'summary' => 'Home, About, FAQs, Gallery, legal pages, footer, agreements.',
            'icon' => 'fa-solid fa-file-lines',
            'file' => 'pages-cms.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'pages',
        ],
        [
            'slug' => 'countries',
            'title' => 'Countries',
            'summary' => 'Admin countries management.',
            'icon' => 'fa-solid fa-map',
            'file' => 'countries.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'countries',
        ],
        [
            'slug' => 'site-settings',
            'title' => 'Site Settings',
            'summary' => 'Settings and menu names.',
            'icon' => 'fa-solid fa-sliders',
            'file' => 'site-settings.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'site_settings',
        ],
        [
            'slug' => 'super-admin',
            'title' => 'Super Admin',
            'summary' => 'Super admin user list / management.',
            'icon' => 'fa-solid fa-shield-halved',
            'file' => 'super-admin.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'admin',
        ],
        [
            'slug' => 'chatbot-assistant',
            'title' => 'Chatbot Assistant',
            'summary' => 'Chatbot dashboard, keywords, and history.',
            'icon' => 'fa-solid fa-comments',
            'file' => 'chatbot-assistant.md',
            'status' => 'coming_soon',
            'sidebar_key' => 'chatbot',
        ],
    ],
];
